version: '3'
services:
  mysql:
    container_name: mysql5.7
    image: arm64v8/mysql
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./local-data:/var/lib/mysql
    ports:
      - "3306:3306"